### ISSUE TITLE
could use better boundaries on glass shape

### ISSUE THREAD

**Issue by bendichter** [dgkf/OpticsSandbox#1]
![image](https://cloud.githubusercontent.com/assets/844306/18063219/fc2105da-6dde-11e6-8875-6e38ff468083.png)

**Comment by dgkf** [comment]
Should be resolved! Check out the improvements at the [Live Demo Page](https://dgkf.github.io/OpticsSandbox/).

This was resolved after reworking the entirety of mouse interactions with objects, making it more generalized and more easily attached to each object. All updates to geometry and constraining of motion is handled via callbacks upon movement of the handle instead of in the update call for the geometry it's bound to.

**Comment by bendichter** [comment]
yeah! Nice work!
