### ISSUE TITLE
spread distance 

### ISSUE THREAD

**Issue by bendichter** [dgkf/OpticsSandbox#6]
![image](https://cloud.githubusercontent.com/assets/844306/18183955/8b3af276-704b-11e6-8c83-203d1332230a.png)

This happens when you try to change the spread distance

**Comment by dgkf** [comment]
Yep! Working on it now. The thresholding on the .html form values is currently placeholder (0-1000 I think). That aside, I need to polish up how the mouse handles and .html forms interact when they are redundant controls for the same object properties. 

These handles working at all is just an artifact of how the mouse handles were reworked. I was really surprised when they reacted at all to input.

**Comment by dgkf** [comment]
Mostly fixed. Marking as closed. There are small cosmetic details like slapping some boundaries on the handles and formatting the numeric values in the .html forms. Otherwise, things are looking pretty good now. 

Check out the updated action over in the [demo page](https://dgkf.github.io/OpticsSandbox/).
